kind: pipeline
type: docker
name: default

steps:
- name: prepare-test-build
  image: node
  volumes:
  # - name: cache
  #   path: /artifacts
  commands:
  - npm install
  - npm run test
  - npm run build

# - name: build-image
#   image: node
#   volumes:
#   - name: cache
#     path: /artifacts
#   commands:
#   - echo "TODO"
#
# - name: push-image
#   image: node
#   volumes:
#   - name: cache
#     path: /artifacts
#   commands:
#   - echo "TODO"

# volumes:
# - name: cache
#   temp: {}

trigger:
  repo:
  - stakwork/sphinx-relay
  - daniel-ro/sphinx-relay
  branch:
  - drone
  - master
