// Original file: proto/signer.proto

export enum SignMethod {
  SIGN_METHOD_WITNESS_V0 = 0,
  SIGN_METHOD_TAPROOT_KEY_SPEND_BIP0086 = 1,
  SIGN_METHOD_TAPROOT_KEY_SPEND = 2,
  SIGN_METHOD_TAPROOT_SCRIPT_SPEND = 3,
}
