// Original file: proto/walletkit.proto

export const WitnessType = {
  UNKNOWN_WITNESS: 'UNKNOWN_WITNESS',
  COMMITMENT_TIME_LOCK: 'COMMITMENT_TIME_LOCK',
  COMMITMENT_NO_DELAY: 'COMMITMENT_NO_DELAY',
  COMMITMENT_REVOKE: 'COMMITMENT_REVOKE',
  HTLC_OFFERED_REVOKE: 'HTLC_OFFERED_REVOKE',
  HTLC_ACCEPTED_REVOKE: 'HTLC_ACCEPTED_REVOKE',
  HTLC_OFFERED_TIMEOUT_SECOND_LEVEL: 'HTLC_OFFERED_TIMEOUT_SECOND_LEVEL',
  HTLC_ACCEPTED_SUCCESS_SECOND_LEVEL: 'HTLC_ACCEPTED_SUCCESS_SECOND_LEVEL',
  HTLC_OFFERED_REMOTE_TIMEOUT: 'HTLC_OFFERED_REMOTE_TIMEOUT',
  HTLC_ACCEPTED_REMOTE_SUCCESS: 'HTLC_ACCEPTED_REMOTE_SUCCESS',
  HTLC_SECOND_LEVEL_REVOKE: 'HTLC_SECOND_LEVEL_REVOKE',
  WITNESS_KEY_HASH: 'WITNESS_KEY_HASH',
  NESTED_WITNESS_KEY_HASH: 'NESTED_WITNESS_KEY_HASH',
  COMMITMENT_ANCHOR: 'COMMITMENT_ANCHOR',
} as const

export type WitnessType =
  | 'UNKNOWN_WITNESS'
  | 0
  | 'COMMITMENT_TIME_LOCK'
  | 1
  | 'COMMITMENT_NO_DELAY'
  | 2
  | 'COMMITMENT_REVOKE'
  | 3
  | 'HTLC_OFFERED_REVOKE'
  | 4
  | 'HTLC_ACCEPTED_REVOKE'
  | 5
  | 'HTLC_OFFERED_TIMEOUT_SECOND_LEVEL'
  | 6
  | 'HTLC_ACCEPTED_SUCCESS_SECOND_LEVEL'
  | 7
  | 'HTLC_OFFERED_REMOTE_TIMEOUT'
  | 8
  | 'HTLC_ACCEPTED_REMOTE_SUCCESS'
  | 9
  | 'HTLC_SECOND_LEVEL_REVOKE'
  | 10
  | 'WITNESS_KEY_HASH'
  | 11
  | 'NESTED_WITNESS_KEY_HASH'
  | 12
  | 'COMMITMENT_ANCHOR'
  | 13

export type WitnessType__Output = typeof WitnessType[keyof typeof WitnessType]
