// Original file: proto/lightning.proto

export const OutputScriptType = {
  SCRIPT_TYPE_PUBKEY_HASH: 'SCRIPT_TYPE_PUBKEY_HASH',
  SCRIPT_TYPE_SCRIPT_HASH: 'SCRIPT_TYPE_SCRIPT_HASH',
  SCRIPT_TYPE_WITNESS_V0_PUBKEY_HASH: 'SCRIPT_TYPE_WITNESS_V0_PUBKEY_HASH',
  SCRIPT_TYPE_WITNESS_V0_SCRIPT_HASH: 'SCRIPT_TYPE_WITNESS_V0_SCRIPT_HASH',
  SCRIPT_TYPE_PUBKEY: 'SCRIPT_TYPE_PUBKEY',
  SCRIPT_TYPE_MULTISIG: 'SCRIPT_TYPE_MULTISIG',
  SCRIPT_TYPE_NULLDATA: 'SCRIPT_TYPE_NULLDATA',
  SCRIPT_TYPE_NON_STANDARD: 'SCRIPT_TYPE_NON_STANDARD',
  SCRIPT_TYPE_WITNESS_UNKNOWN: 'SCRIPT_TYPE_WITNESS_UNKNOWN',
  SCRIPT_TYPE_WITNESS_V1_TAPROOT: 'SCRIPT_TYPE_WITNESS_V1_TAPROOT',
} as const

export type OutputScriptType =
  | 'SCRIPT_TYPE_PUBKEY_HASH'
  | 0
  | 'SCRIPT_TYPE_SCRIPT_HASH'
  | 1
  | 'SCRIPT_TYPE_WITNESS_V0_PUBKEY_HASH'
  | 2
  | 'SCRIPT_TYPE_WITNESS_V0_SCRIPT_HASH'
  | 3
  | 'SCRIPT_TYPE_PUBKEY'
  | 4
  | 'SCRIPT_TYPE_MULTISIG'
  | 5
  | 'SCRIPT_TYPE_NULLDATA'
  | 6
  | 'SCRIPT_TYPE_NON_STANDARD'
  | 7
  | 'SCRIPT_TYPE_WITNESS_UNKNOWN'
  | 8
  | 'SCRIPT_TYPE_WITNESS_V1_TAPROOT'
  | 9

export type OutputScriptType__Output =
  typeof OutputScriptType[keyof typeof OutputScriptType]
