// Original file: proto/lightning.proto

export enum OutputScriptType {
  SCRIPT_TYPE_PUBKEY_HASH = 0,
  SCRIPT_TYPE_SCRIPT_HASH = 1,
  SCRIPT_TYPE_WITNESS_V0_PUBKEY_HASH = 2,
  SCRIPT_TYPE_WITNESS_V0_SCRIPT_HASH = 3,
  SCRIPT_TYPE_PUBKEY = 4,
  SCRIPT_TYPE_MULTISIG = 5,
  SCRIPT_TYPE_NULLDATA = 6,
  SCRIPT_TYPE_NON_STANDARD = 7,
  SCRIPT_TYPE_WITNESS_UNKNOWN = 8,
}
